### ISSUE TITLE
unify config for bimanual / single hand

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-config#19]
Too many duplication

**Comment by ugocupcic** [comment]
Also update to new default values (@jlaforga can set the proper values once we've cleaned up the config).

**Comment by toliver** [comment]
Could this be simply done by removing the single hand parameters and leaving only the rh and lh directories everywhere?

**Comment by toliver** [comment]
Other than that, the duplication is necessary, isn't it?

**Comment by ugocupcic** [comment]
but rh / lf have prefix?

**Comment by toliver** [comment]
In the controller config files, the joint names have prefix (and the controller names have also rh and lh in the name). They are loaded in the root namespace (as that is going to be read by the controller manager and other tools).

But other files, like the calibration, don't have prefixes in the joint names. The motor mapping doesn't have joint names at all, just a list of motor numbers (the index in the list determines the joint). All these parameters are loaded in a namespace (e.g. /rh/joint_to_motor_mapping) if we are defining a hand_id in the launchfile.

**Comment by toliver** [comment]
The way we deal with the mapping should be modified so that we have a set of mapping files for the different hand models:
- right old mapping
- left "
- right new mapping
- left "
- right hand lite
- left "

And then maybe have a launchfile that loads the right one for that hand in the correct directory.
(e.g. mappings/rh/mapping.launch).

**Comment by ugocupcic** [comment]
@jlaforga this could be interesting for you.

The way we'll do it:
- remove all duplication in sr-config 
- add a configuration.yaml file at the root of sr-config that points to the proper config, prefix, type of sensors, serial number, etc...
- move the launch files to sr_edc_launch and unify them using the parameters from the configuration.yaml
- keep the demoes in sr-config for now and run them using `python /etc/shadow/right/demo/....py` instead of the rosrun, with the hope of being able to unify them soon so as to migrate them to the core stack.

To install:
- the config will be installed in: `/etc/shadow/right` or `/etc/shadow/left`
- one branch of sr-config per hand serial number

( @toliver hopefully I didn't forget too much )

**Comment by toliver** [comment]
@jlaforga reminds me that the GUI integration is strictly necessary before we can deploy this as the default.

**Comment by ugocupcic** [comment]
@toliver is talking about the following plugins:
- https://github.com/shadow-robot/sr-visualization/tree/indigo-devel/sr_gui_controller_tuner
- https://github.com/shadow-robot/sr-visualization/tree/indigo-devel/sr_gui_hand_calibration

**Comment by toliver** [comment]
@ugocupcic About the configuration.yaml, do you have anything in mind to use it from the launchfile?
I mean, apparently there's no simple way to read stuff from the parameter server  and use that information to load other stuff in there from a launch file.

So maybe a custom python script should take care of loading the right parameter files?

**Comment by toliver** [comment]
Also if we want to have a simple default branch, all the prefixes (for joint names, for controller names, etc) should be added automatically when loading the parameters. That again suggests that we need a script.

**Comment by ugocupcic** [comment]
I think a custom python script makes sense indeed. It can be called from the launch file directly (like xacro xacro.py).

**Comment by ugocupcic** [comment]
This is what we decided internally:
- remove the non-prefixed configuration. Default to `rh`
- provide python / cpp simple lib to detect hands, joint names / prefixes
- Update ALL GUI plugins to use prefix
- Keep all mapping files as a list. Use a yaml parameter to point to the proper mapping for a given hand.
- Update documentation for config and launch

Closing this issue and splitting it.
