### ISSUE TITLE
Better names for hand mappings

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-config#38]
File names in https://github.com/shadow-robot/sr-ros-interface-ethercat/tree/indigo-devel/sr_edc_launch/mappings/default_mappings are not very accurate, as in fact all the hand models there are ethercat, so rh_ethercat.yaml is confusing.

@jlaforga proposes:
- rh_e.yaml for hand E
- rh_g.yaml for hand G (unofficially called lite, but officially called G)
  ...

Te muscle ones are fine.

**Comment by kirstyellis** [comment]
If we are going to change the names of the files, while we do this could we also add the old mappings that are missing. Guillaume recently had an issue with the mapping as he used the defaults but he has an older type hand. The mapping for this type of hand has not yet been added to default_mappings.

**Comment by kirstyellis** [comment]
fixed
