### ISSUE TITLE
Dependency problem with industrial_extrinsic_cal

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-config#60]
For the moment this package is not released.

This is causing problems as rosdep doesn't find it (see [this](https://semaphoreci.com/shadow-robot/sr-ros-interface-ethercat/branches/pull-request-128/builds/1))

We should create a repository.rosinstall to install it from source (or temporarily remove the dependency).

**Comment by toliver** [comment]
We have agreed to create a separate repo for these configurations: `sr_vision_config`, or would it be better `sr_camera_config`?

**Comment by ugocupcic** [comment]
happy with either
